services:
    home_web:
        container_name: home_web
        image: nginx:alpine
        ports:
            - "9002:80"
        volumes:
            - ./:/var/www
            - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - home_app
        networks:
            - home_network
    home_app:
        container_name: home_app
        build:
            context: .
            dockerfile: ./docker/Dockerfile
        depends_on:
            - home_db
        volumes:
            - ./:/var/www
        networks:
            - home_network
        ports:
            - "9080:9001"
    home_db:
        image: mysql
        container_name: home_db
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
        volumes:
            - home_database:/var/lib/mysql
        networks:
            - home_network
        ports:
            -   "3210:3306"
    home_node:
        image: node:22
        container_name: home_node
        working_dir: /var/www
        volumes:
            - ./:/var/www
        tty: true
        ports:
            - "5173:5173"  # For Vite development server
        environment:
            - NODE_ENV=development
        command: >
            sh -c "npm install && npm run build"
        networks:
            - home_network
networks:
    home_network:
        driver: bridge
volumes:
    home_database:


